#Example TOML file for an axial turbine blade. This blade is based on the VKI transonic turbine (add ref)

name = "Axial Turbine"
units = 'metres'
axis = [ [0.0,0.0,0.0] , [0.0,0.0,1.0] ]
n_blade = 100

ps_section_fname = 'vki_ps.fpd'
ss_section_fname = 'vki_ss.fpd'

endwall_type = 'step'
endwall_fname ='with_cavity.step'